print("   ")
print("   ")
print("    ___  _ __   ___      | (_)_ __   ___  ")
print("   / _ \| '_ \ / _ \_____| | | '_ \ / _ \ ")
print("  | (_) | | | |  __/_____| | | | | |  __/ ")
print("   \___/|_| |_|\___|     |_|_|_| |_|\___| ")
print("   ")
print("   ")
print("   ")
print("   ")

ml=int(input("plase enter two seconds: "))
print (f' \nis:  [[{ml//3600} hours]] \n|| and ||  \nis: [[{(ml%3600)//60} min]] \n|| and ||  \nis: [[{ml%60} seconds]]')
print('')
print('')
print('')

