print(             '♜♞♝♚♛♝♞♜')
print(             '♟♟♟♟♟♟♟♟')
print(             '▓░▓░▓░▓░▓░▓░')
print(             '░▓░▓░▓░▓░▓░▓')
print(             '▓░▓░▓░▓░▓░▓░')
print(             '░▓░▓░▓░▓░▓░▓')
print(             '♙♙♙♙♙♙♙♙')
print(             '♖♘♗♔♕♗♘♖')

s=input("enter to number min: ")
d=(float(s)//(60))
b=(float(s)%(60))
print('')
print("this tame is the: \n""  --------------------------------  ""\n[[| "  + (str(d)) + " houers"  " and: " + (str(b)) + " min |]]")
print("  --------------------------------  ")
print("(\_____ _____ _____/)")
print(" ------( o o )------")
print("        \   /")
print("        ('_')")

